version: 2
jobs:
  build:
    working_directory: ~/itk_queue
    environment:
      - MIX_ENV: test
    docker:
      - image: circleci/elixir:1.8
      - image: rabbitmq:3.7
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

notify:
  webhooks:
    - url: https://itk-webhook.ucoachapp.com/circle
